# work directory where the listed repositories are located
workdir: /home/user/codesync

# the remote url prefix lets you change the protocol or use a different git server
# - for SSL use: 'git@github.com:'
# - for HTTPS use: 'https://github.com/'
remote_url_prefix: 'git@github.com:'

# clone projects if they do not exist
clone: false

# remove projects if they are not listed (i.e. moves them into a folder 'removed')
remove: false

# if command output should be redirected to stdout
verbose: false

# list of organisations to be processes
orgs:
  - myuser
  - myorg

# list of repositories to be processes if the org is listed
repos:
  myuser:
    - repo-a
    - repo-b
    - repo-c
  myorg:
    - work
