# work directory where the listed repositories are located
workdir: /home/anliksim/codebase/sync/
git_user: anliksim
# if command output should be redirected to stdout
verbose: false

# list of repositories to be processes
repos:
  - zhaw-pspp-lab10
  - zhaw-pspp-lab9
  - zhaw-pspp-lab8
  - zhaw-pspp-lab4
