# work directory where the listed repositories are located
workdir: /home/anliksim/codebase/sync/
# clone projects if they do not exist
clone: false
# if command output should be redirected to stdout
verbose: false

# list of organisations to be processes
orgs:
  anliksim
  yeahlow-ch

# list of repositories to be processes if the org is listed
repos:
  anliksim:
    - zhaw-pspp-lab10
    - zhaw-pspp-lab9
    - zhaw-pspp-lab8
    - zhaw-pspp-lab4
  yeahlow-ch:
    - yeahlow-represaents
    - yeahlow-abc
